### ISSUE TITLE
[ENH] Group the temporary visualization files in a single folder

### ISSUE THREAD

**Issue by oalifdal** [opentraveldata/geobases#11]
When visualizing data using map frontend `GeoBase --map`, the necessary files (html, json, png, ...) are automatically generated in the working directory at the top level. 

The script gives a hint of the list of files generated (it even gives the actual command to remove them), I think it would be more convenient if all the files were created in one sub-folder that the user would remove afterwards, or keep for later use.

**Comment by alexprengere** [comment]
Good idea. Since this is not a big change, I implemented it directly on the `public` branch for this version:
- 5ab8abb169d1d57d51b7e654b79673749896c6a6 for the Python API
- 1d607b30d533576b0e35900b8c78a3902aa79d67 for command line

Access with command line with `-D/--output-dir`. Default is still the current directory though (this may change in the future):

``` bash
$ GeoBase SFO CDG --map -D tmp
```
