### ISSUE TITLE
Use on Google App Engine

### ISSUE THREAD

**Issue by katychuang** [opentraveldata/geobases#15]
CACHE_DIR variable not working for me. here's the error output:

File "/home/frame/views.py", line 22, in <module>
    from GeoBases import GeoBase
  File "/home/GeoBases/**init**.py", line 9, in <module>
    from .GeoBaseModule        import GeoBase, DEFAULTS
  File "/home/GeoBases/GeoBaseModule.py", line 66, in <module>
    from .SourcesManagerModule import SourcesManager
  File "/home/GeoBases/SourcesManagerModule.py", line 68, in <module>
    os.makedirs(CACHE_DIR)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/python/stubs.py", line 39, in os_error_not_implemented
    raise OSError(errno.ENOSYS, 'Function not implemented')
OSError: [Errno 78] Function not implemented

I notice that the variable is declared in SourcesManagerModule.py, CACHE_DIR = op.join(os.getenv('HOME', '.'), '.GeoBases.d', CACHE_TAG) would this directory need to be created in my GAE home directory beforehand?

**Comment by alexprengere** [comment]
Indeed, when you first import the package, it will try to create a cache directory in `op.join(os.getenv('HOME', '.'), '.GeoBases.d', CACHE_TAG)`, this is usually in `~/GeoBases.d/main`.
Since this directory is in user space, there is usually no problem creating the directory.

I have no experience with Google App Engine, but from [what I found](http://stackoverflow.com/questions/2693081/does-google-app-engine-allow-creation-of-files-and-folders-on-the-server), it does not seem possible to write on the filesystem.

I will try to solve this problem by removing cache mechanism when `CACHE_DIR` failed to create. Can you tell me which Python version you used?

**Comment by katychuang** [comment]
Sure, I'm using python version 2.7

**Comment by katychuang** [comment]
Btw, I am trying to attach this library to use with a flask app

**Comment by alexprengere** [comment]
I just pushed 330156b05d76d3395f7041317118827ae3562cea (on all branches). This should fix your problem. I did not yet update PyPI packages.

Basically, in the sources management part of the code:
- `os.makedirs` calls are now protected from `OSError`
- `shutil.copy` calls are protected from `IOError`

If you intend to use the _visualization_ methods, it will still fail, since there are `shutil.copy` and `os.makedirs` calls in the visualization code.
I see no point in catching errors for this part, since visualization is based on writing HTML/Json/Js files for the browser to be read. If you cannot write files on GAE, catching the errors when writing will not help you. But you should be able to write the HTML/Json/Js files locally then upload them on any web server.

I hope I answered your problem, please let me know how it goes, and thank you for reporting this problem.

**Comment by katychuang** [comment]
Hmm.. so after commenting out lines 67-71 of SourcesManagerModule.py, there's another error with imports. Searched around for Levenshtein, it looks like it's written in C which may not run on GAE. I may have to use a different web host for my app.

Traceback (most recent call last):
  File "/home/main.py", line 3, in <module>
    from frame import app
  File "/home/frame/**init**.py", line 7, in <module>
    import views
  File "/home/frame/views.py", line 17, in <module>
    from GeoBases import GeoBase
  File "/home/GeoBases/**init**.py", line 9, in <module>
    from .GeoBaseModule        import GeoBase, DEFAULTS
  File "/home/GeoBaseModule.py", line 68, in <module>
    from .LevenshteinUtils     import mod_leven, clean
  File "/home/GeoBases/LevenshteinUtils.py", line 36, in <module>
    from Levenshtein import ratio as LevenRatio
ImportError: No module named Levenshtein

**Comment by alexprengere** [comment]
I don't know if you wrote your post after of before mine :).

If you pull the last version, you should not have to comment anything in the _SourcesManagerModule_.
_Levenshtein_ is a Python module that you have to install as a third-party, as described in the `setup.py` file.

If you cannot use C based extensions, no problem! You may be interested in the `pypy` branch, which contain only pure Python dependencies. In this branch, the _Levenshtein_ module is stubbed using _difflib_. So just do a `git checkout pypy` and this should work on GAE. 

On PyPI, the `pypy` branch is packaged as [_GeoBasesPypy_](https://crate.io/packages/GeoBasesPypy) (if you want to list it in a `setup.py` file).

**Comment by katychuang** [comment]
with pypy branch, I run into IO errors

/home/GeoBases/GeoBaseModule.py", line 2965, in visualize
    with open(json_name, 'w') as out:
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/python/stubs.py", line 245, in **init**
    raise IOError(errno.EROFS, 'Read-only file system', filename)
IOError: [Errno 30] Read-only file system: './example_map.json'

**Comment by alexprengere** [comment]
This is completely normal. As I said in the second comment, the `visualize()` method has one purpose: writing HTML/Json/Js files in the current directory (or the one specified with `output_dir`), then serve them with _SimpleHTTPServer_.

If you are using Google App Engine, you will not be able to successfully execute these visualization methods, since you cannot write anything on the filesystem. Catching these errors in _GeoBases_ would be pointless, since I think you _want_ to get the _IOError_ at this point (in the _SourcesManagerModule_, that was different, we did not _need_ the cache, it was just useful).

But that's not the end of it! I think another "flow" would be to generate the static files locally (without using `dev_appserver.py`), then upload the static files on GAE to serve them. This is just for the visualization methods, other methods (those who do not write anything) should work directly on GAE. Another benefit: if you generate the files locally, you can use the _public_ branch, you won't have to worry about C modules not running.

Right now I do not see another way to use _GeoBases_ visualizations on GAE :).

**Comment by katychuang** [comment]
Ah, ok that makes sense. I appreciate your patience in explaining the code. 

Yes, I agree that using GAE requires generating files locally then uploading them. Alternatively, someone suggested using AWS Beanstalk as a host for creating visualizations on the fly. I'l try both methods to see which works better and let you know the outcomes.

**Comment by alexprengere** [comment]
Ok thanks! If you need support, or feel like some documentation/feature is missing, please let me know :).
